### ISSUE TITLE
If text contains Chinese or Japanese text, the output notification becomes "garbled"

### ISSUE THREAD

**Issue by ms7m** [ms7m/notify-py#22]
Example result with message as "虛實"
![image](https://user-images.githubusercontent.com/37344632/98766408-172be880-23ad-11eb-8c0d-237a47346086.png)

**Comment by ms7m** [comment]
Possible solution: https://github.com/go-toast/toast/issues/18#issuecomment-532605509

**Comment by WingDust** [comment]
how to fix it

**Comment by ms7m** [comment]
This issue has been fixed in version 0.3.1.

Thanks to @WingDust for the PR containing the fix!
785d319a916ab03d2d110b8dafcc585b3ac9b7a8 & 4d30f3b8266d4e4184c5c15e33518fef597ff1b1
