### ISSUE TITLE
Application name is `notify-send` on Linux

### ISSUE THREAD

**Issue by Bertik23** [ms7m/notify-py#27]
If I use `Notify().send()` I get this notification:
![obrazek](https://user-images.githubusercontent.com/39457484/111025641-b4dc0680-83e5-11eb-8412-d3cdc9c024c9.png)
The application name is `notify-send` instead of `Python Application (notify.py)`
That could be fixed by adding `application_name` as a argument to `LinuxNotifier.send_notification` and adding
```py
if application_name:
    generated_command.append(f"--app-name={shlex.quote(application_name)}")
```

this issue will be fixed in v0.3.2 when using Dbus, but not when using the legacy notifier.

**Comment by ms7m** [comment]
Thanks -- I'll try to push this change in v0.3.2.
