### ISSUE TITLE
Powershell prompt will appear if audio is passed.

### ISSUE THREAD

**Issue by Zac8668** [ms7m/notify-py#29]
When I try to make an exe of my python program with pyinstaller if the notification has audio an powershell prompt pops up.
The paremeters I used were: --onefile --noconsole

**Comment by padmalcom** [comment]
Same here, took me a while to figure out the promt only appears when playing audio files.

**Comment by padmalcom** [comment]
Thanks, can you push it to pypi?

**Comment by ms7m** [comment]
@padmalcom planning to do so hopefully later today.. I'll be near my Windows PC later for a couple more tests for pyinstaller..

If you need access *now*, I can provide a wheel

**Comment by padmalcom** [comment]
@ms7m Thanks, I did a pip install from the latest commit of this repo but the problem still exists. The Powershell window keeps popping up when I play a custom sound.

**Comment by ms7m** [comment]
Did you try from the ``dev`` branch? I just tried a [sample Pyinstaller app](https://gist.github.com/ms7m/deae8c0c6e9bf7a90dd4b556c7395e6e) and I no longer see the issue?

**Comment by ms7m** [comment]
Go ahead and try to unzip this file and 

```
pip install notify_py-0.3.2-py3-none-any.whl
```

[notify_py-0.3.2.zip](https://github.com/ms7m/notify-py/files/6407562/notify_py-0.3.2.zip)

**Comment by padmalcom** [comment]
Works fine, thank you!
