### ISSUE TITLE
TypeError: WindowsNotifier.__init__() got an unexpected keyword argument 'default_application_name'

### ISSUE THREAD

**Issue by Lucas-Niesen** [ms7m/notify-py#46]
I tried this code but it doen't work.
![image](https://user-images.githubusercontent.com/46261961/192816907-daf28587-0527-487d-bfa2-09eae73aa950.png)

**Comment by Lucas-Niesen** [comment]
Is there a temporary fix for this?

**Comment by ms7m** [comment]
I'll push out a fix for this, but a quick way to fix this is to use the ``WindowsNotifier.send_notification`` method directly. This would only work out if you know your target platform is windows.

**Comment by Lucas-Niesen** [comment]
> I'll push out a fix for this, but a quick way to fix this is to use the `WindowsNotifier.send_notification` method directly. This would only work out if you know your target platform is windows.

But how can i change the name?
![image](https://user-images.githubusercontent.com/46261961/194413650-e4764997-093c-4970-b57a-15b22527e403.png)

**Comment by ms7m** [comment]
You can pass ``application_name`` parameter to ``WindowsNotifier.send_notification`` with the name you'd like.

**Comment by ms7m** [comment]
I'm not near a windows computer to verify but you should be able to do something like this:

```python
from notifypy.os_notifiers.windows import WindowsNotifier

WindowsNotifier().send_notification(
        notification_title="Sample Title",
        notification_subtitle="Sample Subtitle",
        notification_icon="path_to_icon.ico",
        application_name="Goat IM",
        notification_audio="path_to_audio.mp3",
)
```

lmk if it works out for you.

**Comment by Lucas-Niesen** [comment]
The sound works but i dont see any message on my screen.
![image](https://user-images.githubusercontent.com/46261961/194416704-8966a08f-9e6b-4391-b3e1-4a8cd5ccc5f5.png)

**Comment by ms7m** [comment]
Might be an issue with the latest versions of Windows -- I won't be back near my desk until the end of the day. I'll take a look at then.

**Comment by Lucas-Niesen** [comment]
> Might be an issue with the latest versions of Windows -- I won't be back near my desk until the end of the day. I'll take a look at then.

So i tried it on win 10 21H2 and win 11 21H2 but it doesn't work on both.

**Comment by mniesen** [comment]
> I tried this code but it doen't work. ![image](https://user-images.githubusercontent.com/46261961/192816907-daf28587-0527-487d-bfa2-09eae73aa950.png)

Changing ```default_application_name``` to ```default_notification_application_name``` works for me after running function your_function.

Code looks like:
```
from notifypy import Notify

notification = Notify(
    default_notification_title="Function Message",
    default_notification_application_name="Great Application",
    default_notification_icon="test.ico"
)

def your_function():
  # stuff happening here.
  notification.message = "Function Result"
  notification.send()

your_function()
```

In the README.md file the example used default_application_name, this give me an error as well.
