### ISSUE TITLE
Suppress logging output by default

### ISSUE THREAD

**Issue by AuHau** [ms7m/notify-py#7]
When I am sending notification I get bunch of logging output into the terminal. Since this is a library people might not be really interested in this logging by default. For example, I am using it in CLI application and there it is very distracting and not required.

Can you please by default turn it off? Maybe it could be turned on with a flag in options of the constructor? Or environmental variable? I logging will be used only in debugging scenario.

**Comment by ms7m** [comment]
Thanks Adam,

v0.2.2 fixes this.

To re-enable logging 

```python
from notifypy import Notify

n = Notify(enable_logging=True)

n.send()
```

Cheers

**Comment by AuHau** [comment]
Sweet! Thanks again for such a prompt answer! 

Good luck on your journey 🙂
